name: Build Test

on:
  pull_request:
    branches:
      - master
  push:
    branches-ignore:
      - master

jobs:
  test-build:
    name: Test Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true

      - name: Build Vite app
        run: npm run build

      - name: Package Electron (no installer)
        run: npm run pack
        continue-on-error: true

      - name: List output
        run: ls -R release/
        if: runner.os != 'Windows'

      - name: List output (Windows)
        run: Get-ChildItem -Path release -Recurse
        if: runner.os == 'Windows'
        shell: powershell
